version: "3.9"
services:
  postgres-1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "SHISHLYANNIKOV_205"
      POSTGRES_USER: "SHISHLYANNIKOV_205"
      POSTGRES_PASSWORD: "SHISHLYANNIKOV_205"
      PGDATA: "/var/lib/postgresql/data/pgdata_lib"
    volumes:
      - ./docker/db/scripts:/Library/library.sql
    ports:
      - "5432:5432"

  postgres-2:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "SHISHLYANNIKOV_205"
      POSTGRES_USER: "SHISHLYANNIKOV_205"
      POSTGRES_PASSWORD: "SHISHLYANNIKOV_205"
      PGDATA: "/var/lib/postgresql/data/pgdata_train"
    volumes:
      - ./docker/db/scripts:/Train/Train.sql
    ports:
      - "5433:5432"

  postgres-3:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "SHISHLYANNIKOV_205"
      POSTGRES_USER: "SHISHLYANNIKOV_205"
      POSTGRES_PASSWORD: "SHISHLYANNIKOV_205"
      PGDATA: "/var/lib/postgresql/data/pgdata_hospital"
    volumes:
      - ./docker/db/scripts:/Hospital.Hospital.sql
    ports:
      - "5434:5432"